theme: jekyll-theme-midnight
title: Coffee and tea
description: Support good causes by getting quality coffee and tea  <br /><span style="font-size:70%">Facilitated by Plan B Vineyard, Trondheim</span>
